/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClassementRouteImport } from './routes/classement'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoteSlugRouteImport } from './routes/vote.$slug'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as VoteConfirmRefRouteImport } from './routes/vote.confirm.$ref'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments.webhook'

const ClassementRoute = ClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteSlugRoute = VoteSlugRouteImport.update({
  id: '/vote/$slug',
  path: '/vote/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteConfirmRefRoute = VoteConfirmRefRouteImport.update({
  id: '/vote/confirm/$ref',
  path: '/vote/confirm/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classement': typeof ClassementRoute
  '/c/$slug': typeof CSlugRoute
  '/vote/$slug': typeof VoteSlugRoute
  '/vote/confirm/$ref': typeof VoteConfirmRefRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classement': typeof ClassementRoute
  '/c/$slug': typeof CSlugRoute
  '/vote/$slug': typeof VoteSlugRoute
  '/vote/confirm/$ref': typeof VoteConfirmRefRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classement': typeof ClassementRoute
  '/c/$slug': typeof CSlugRoute
  '/vote/$slug': typeof VoteSlugRoute
  '/vote/confirm/$ref': typeof VoteConfirmRefRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classement'
    | '/c/$slug'
    | '/vote/$slug'
    | '/vote/confirm/$ref'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classement'
    | '/c/$slug'
    | '/vote/$slug'
    | '/vote/confirm/$ref'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/classement'
    | '/c/$slug'
    | '/vote/$slug'
    | '/vote/confirm/$ref'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassementRoute: typeof ClassementRoute
  CSlugRoute: typeof CSlugRoute
  VoteSlugRoute: typeof VoteSlugRoute
  VoteConfirmRefRoute: typeof VoteConfirmRefRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/classement': {
      id: '/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof ClassementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/$slug': {
      id: '/vote/$slug'
      path: '/vote/$slug'
      fullPath: '/vote/$slug'
      preLoaderRoute: typeof VoteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/confirm/$ref': {
      id: '/vote/confirm/$ref'
      path: '/vote/confirm/$ref'
      fullPath: '/vote/confirm/$ref'
      preLoaderRoute: typeof VoteConfirmRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassementRoute: ClassementRoute,
  CSlugRoute: CSlugRoute,
  VoteSlugRoute: VoteSlugRoute,
  VoteConfirmRefRoute: VoteConfirmRefRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
