/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ClassementRouteImport } from './routes/classement'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoteSlugRouteImport } from './routes/vote.$slug'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as VoteSuccessRefRouteImport } from './routes/vote.success.$ref'
import { Route as VoteEchecRefRouteImport } from './routes/vote.echec.$ref'
import { Route as VoteAttenteRefRouteImport } from './routes/vote.attente.$ref'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments.webhook'

const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassementRoute = ClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteSlugRoute = VoteSlugRouteImport.update({
  id: '/vote/$slug',
  path: '/vote/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteSuccessRefRoute = VoteSuccessRefRouteImport.update({
  id: '/vote/success/$ref',
  path: '/vote/success/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteEchecRefRoute = VoteEchecRefRouteImport.update({
  id: '/vote/echec/$ref',
  path: '/vote/echec/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteAttenteRefRoute = VoteAttenteRefRouteImport.update({
  id: '/vote/attente/$ref',
  path: '/vote/attente/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/classement': typeof ClassementRoute
  '/maintenance': typeof MaintenanceRoute
  '/c/$slug': typeof CSlugRoute
  '/vote/$slug': typeof VoteSlugRoute
  '/vote/attente/$ref': typeof VoteAttenteRefRoute
  '/vote/echec/$ref': typeof VoteEchecRefRoute
  '/vote/success/$ref': typeof VoteSuccessRefRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/classement': typeof ClassementRoute
  '/maintenance': typeof MaintenanceRoute
  '/c/$slug': typeof CSlugRoute
  '/vote/$slug': typeof VoteSlugRoute
  '/vote/attente/$ref': typeof VoteAttenteRefRoute
  '/vote/echec/$ref': typeof VoteEchecRefRoute
  '/vote/success/$ref': typeof VoteSuccessRefRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/classement': typeof ClassementRoute
  '/maintenance': typeof MaintenanceRoute
  '/c/$slug': typeof CSlugRoute
  '/vote/$slug': typeof VoteSlugRoute
  '/vote/attente/$ref': typeof VoteAttenteRefRoute
  '/vote/echec/$ref': typeof VoteEchecRefRoute
  '/vote/success/$ref': typeof VoteSuccessRefRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/classement'
    | '/maintenance'
    | '/c/$slug'
    | '/vote/$slug'
    | '/vote/attente/$ref'
    | '/vote/echec/$ref'
    | '/vote/success/$ref'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/classement'
    | '/maintenance'
    | '/c/$slug'
    | '/vote/$slug'
    | '/vote/attente/$ref'
    | '/vote/echec/$ref'
    | '/vote/success/$ref'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/classement'
    | '/maintenance'
    | '/c/$slug'
    | '/vote/$slug'
    | '/vote/attente/$ref'
    | '/vote/echec/$ref'
    | '/vote/success/$ref'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ClassementRoute: typeof ClassementRoute
  MaintenanceRoute: typeof MaintenanceRoute
  CSlugRoute: typeof CSlugRoute
  VoteSlugRoute: typeof VoteSlugRoute
  VoteAttenteRefRoute: typeof VoteAttenteRefRoute
  VoteEchecRefRoute: typeof VoteEchecRefRoute
  VoteSuccessRefRoute: typeof VoteSuccessRefRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classement': {
      id: '/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof ClassementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/$slug': {
      id: '/vote/$slug'
      path: '/vote/$slug'
      fullPath: '/vote/$slug'
      preLoaderRoute: typeof VoteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/success/$ref': {
      id: '/vote/success/$ref'
      path: '/vote/success/$ref'
      fullPath: '/vote/success/$ref'
      preLoaderRoute: typeof VoteSuccessRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/echec/$ref': {
      id: '/vote/echec/$ref'
      path: '/vote/echec/$ref'
      fullPath: '/vote/echec/$ref'
      preLoaderRoute: typeof VoteEchecRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/attente/$ref': {
      id: '/vote/attente/$ref'
      path: '/vote/attente/$ref'
      fullPath: '/vote/attente/$ref'
      preLoaderRoute: typeof VoteAttenteRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ClassementRoute: ClassementRoute,
  MaintenanceRoute: MaintenanceRoute,
  CSlugRoute: CSlugRoute,
  VoteSlugRoute: VoteSlugRoute,
  VoteAttenteRefRoute: VoteAttenteRefRoute,
  VoteEchecRefRoute: VoteEchecRefRoute,
  VoteSuccessRefRoute: VoteSuccessRefRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
